#!/usr/bin/env python3
"""Generate the `quick-reference` global rule from what is actually on disk.

Reads agents/*.md, skills/*/SKILL.md and skills/*/scripts/*.py under this kit and writes a
catalog rule (agents + triggers, skills + one-line descriptions, slash commands, scripts).

Usage:
    python build_quick_reference.py                  # prints to stdout
    python build_quick_reference.py --write          # writes C:/Users/Keith/.gemini/config/rules/quick-reference.md
    python build_quick_reference.py --out <path>
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

KIT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = Path.home() / ".gemini" / "config" / "rules" / "quick-reference.md"
KIT_URL = "C:/Users/Keith/.gemini/config/plugins/ag-kit-v2"


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text("utf-8", errors="replace")
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    data: dict[str, str] = {}
    if not match:
        return data
    current = None
    for line in match.group(1).splitlines():
        field = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if field:
            current, value = field.groups()
            data[current] = value.strip().strip("\"'")
        elif current and line.startswith((" ", "\t")):
            data[current] = (data[current] + " " + line.strip().strip("\"'")).strip()
    return data


def one_line(text: str, limit: int = 140) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def build() -> str:
    agents = []
    for path in sorted((KIT / "agents").glob("*.md")):
        data = frontmatter(path)
        desc = data.get("description", "")
        trig = re.search(r"Triggers on:\s*(.*)$", desc)
        agents.append((path.stem, one_line(trig.group(1).rstrip(". "), 90) if trig else one_line(desc, 90)))

    commands, skills = [], []
    for path in sorted((KIT / "skills").glob("*/SKILL.md")):
        data = frontmatter(path)
        desc = data.get("description", "")
        if desc.startswith("/"):
            commands.append((path.parent.name, one_line(desc.split("—", 1)[-1].split(" - ", 1)[-1], 110)))
        else:
            skills.append((path.parent.name, one_line(desc, 120)))

    scripts = [f"scripts/{p.name}" for p in sorted((KIT / "scripts").glob("*.py"))]
    scripts += [f"skills/{p.parent.parent.name}/scripts/{p.name}" for p in sorted((KIT / "skills").glob("*/scripts/*.py"))]

    lines = [
        "---",
        "name: quick-reference",
        "version: 2.0.0",
        "priority: P2",
        "trigger: model_decision",
        "description: Catalog of the kit's agents (with trigger keywords), skills, slash commands, and scripts. Apply when deciding which agent or skill fits, or when looking up a script path. Generated by scripts/build_quick_reference.py — do not edit by hand.",
        "---",
        "",
        "# Quick Reference (generated)",
        "",
        f"Kit root: `{KIT_URL}`. Agents are files under `agents/`; skills under `skills/<name>/SKILL.md`; every skill is also the slash command `/<name>`.",
        "",
        f"## Agents ({len(agents)})",
        "| Agent | Triggers |",
        "|---|---|",
    ]
    lines += [f"| {name} | {trig} |" for name, trig in agents]
    lines += ["", f"## Slash commands ({len(commands)})", "| Command | Does |", "|---|---|"]
    lines += [f"| /{name} | {desc} |" for name, desc in commands]
    lines += ["", f"## Skills ({len(skills)})", "| Skill | Use when |", "|---|---|"]
    lines += [f"| {name} | {desc} |" for name, desc in skills]
    lines += ["", f"## Scripts ({len(scripts)}) — run as `python {KIT_URL}/<path> <project>`"]
    lines += [f"- `{s}`" for s in scripts]
    lines += ["", "Required gate scripts (`checklist.py`): security_scan, lint_runner, type_coverage, test_runner. Everything else is advisory.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the quick-reference rule from disk")
    parser.add_argument("--write", action="store_true", help=f"write to {DEFAULT_OUT}")
    parser.add_argument("--out", type=Path, help="write to this path instead")
    args = parser.parse_args()
    content = build()
    target = args.out or (DEFAULT_OUT if args.write else None)
    if target is None:
        print(content)
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {target} ({len(content.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
